# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
compiler: gcc

before_install:
  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  sudo apt-get -qq update
  sudo apt-get -qq install g++-4.8

sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
