// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// irtppinterface
Rcpp::List irtppinterface(Rcpp::IntegerMatrix data, int e_model, Rcpp::NumericMatrix quads);
RcppExport SEXP IRTpp_irtppinterface(SEXP dataSEXP, SEXP e_modelSEXP, SEXP quadsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type data(dataSEXP );
        Rcpp::traits::input_parameter< int >::type e_model(e_modelSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type quads(quadsSEXP );
        Rcpp::List __result = irtppinterface(data, e_model, quads);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
