# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('IRTpp_rcpp_hello_world', PACKAGE = 'IRTpp')
}

timesTwo <- function(x) {
    .Call('IRTpp_timesTwo', PACKAGE = 'IRTpp', x)
}

cpower <- function(x) {
    .Call('IRTpp_cpower', PACKAGE = 'IRTpp', x)
}

