# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irtpp <- function(data, nameOfModel, dim, nameOfInitVal, vEpsilonConv, maxIt, vVerbose) {
    .Call('IRTpp_irtpp', PACKAGE = 'IRTpp', data, nameOfModel, dim, nameOfInitVal, vEpsilonConv, maxIt, vVerbose)
}

timesTwo <- function(x) {
    .Call('IRTpp_timesTwo', PACKAGE = 'IRTpp', x)
}

cpower <- function(x) {
    .Call('IRTpp_cpower', PACKAGE = 'IRTpp', x)
}

