# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irtpp <- function(data, nameOfModel, dim, nameOfInitVal, vEpsilonConv, maxIt, vVerbose) {
    .Call('IRTpp_irtpp', PACKAGE = 'IRTpp', data, nameOfModel, dim, nameOfInitVal, vEpsilonConv, maxIt, vVerbose)
}

itemfitpp <- function(parametersO, data, scores, nameOfModel, vVerbose) {
    .Call('IRTpp_itemfitpp', PACKAGE = 'IRTpp', parametersO, data, scores, nameOfModel, vVerbose)
}

